version: '3.9'

#  1.5 CPUs = 0.7 MongoDB + 2 x 0.35 Spring Boot + 0.05 Redis + 0.05 NGinx
#    3.0 GB = 0.65 MongoDB + 2 x 1.10 Spring Boot + 0.05 Redis + 0.10 NGinx

services:
  spring-api1:
    image: boaglio/rinhabackend2023:latest
    hostname: spring-api1
    environment:
      - SERVER_PORT=8080
      - MARIADB_URI=mongodb://db-mongodb:27017/rinhadb?socketTimeoutMS=360000&connectTimeoutMS=360000&maxPoolSize=50&minPoolSize=50
      - jdbc:mariadb://localhost:3306/rinha_db?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    depends_on:
      - mariadb
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '1.1GB'
    networks:
      - rinha_backend2023_q3_java_network


  spring-api2:
    image: boaglio/rinhabackend2023:latest
    hostname: spring-api2
    environment:
      - SERVER_PORT=8080
      - MARIADB_URI=mongodb://db-mongodb:27017/rinhadb?socketTimeoutMS=360000&connectTimeoutMS=360000&maxPoolSize=50&minPoolSize=50
    depends_on:
      - mariadb
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '1.1GB'
    networks:
      - rinha_backend2023_q3_java_network


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-api1
      - spring-api2
    ports:
      - "9999:9999"
    networks:
      - rinha_backend2023_q3_java_network
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '0.1GB'

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rinha_db
      MYSQL_USER: rinha_user
      MYSQL_PASSWORD: rinha2023
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '0.65GB'
    networks:
      - rinha_backend2023_q3_java_network

networks:
  rinha_backend2023_q3_java_network: