server:
  port: ${PORT:8080}
  tomcat:
    connection-timeout: 120000 # Tempo limite de conexão (em milissegundos)
    max-connections: 1000  # Número máximo de conexões simultâneas
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/rinha_db?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    username: rinha_user
    password: rinha2023
    schemas:
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        maxLifetime: 500
        rewriteBatchedStatements: true
        idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.boot.autoconfigure.logging: info
    org.springframework.web: info
    org.springframework.jdbc: info
    org.springframework.data: debug
    com.zaxxer.hikari: debug
    redis.clients.jedis: debug
    com.luizrossetti.rinhabackend2023q3java: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug